
package com.cjp.spitter.client.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpitterServiceEndpoint", targetNamespace = "http://jaxws.spitter.cjp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpitterServiceEndpoint {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addSpittle", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.AddSpittle")
    @ResponseWrapper(localName = "addSpittleResponse", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.AddSpittleResponse")
    @Action(input = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/addSpittleRequest", output = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/addSpittleResponse")
    public void addSpittle(
        @WebParam(name = "arg0", targetNamespace = "")
        Spittle arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSpittle", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.DeleteSpittle")
    @ResponseWrapper(localName = "deleteSpittleResponse", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.DeleteSpittleResponse")
    @Action(input = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/deleteSpittleRequest", output = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/deleteSpittleResponse")
    public void deleteSpittle(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.cjp.spitter.client.jaxws.Spittle>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecentSpittles", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.GetRecentSpittles")
    @ResponseWrapper(localName = "getRecentSpittlesResponse", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.GetRecentSpittlesResponse")
    @Action(input = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/getRecentSpittlesRequest", output = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/getRecentSpittlesResponse")
    public List<Spittle> getRecentSpittles(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.cjp.spitter.client.jaxws.Spittle>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSpittlesForSpitter", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.GetSpittlesForSpitter")
    @ResponseWrapper(localName = "getSpittlesForSpitterResponse", targetNamespace = "http://jaxws.spitter.cjp.com/", className = "com.cjp.spitter.client.jaxws.GetSpittlesForSpitterResponse")
    @Action(input = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/getSpittlesForSpitterRequest", output = "http://jaxws.spitter.cjp.com/SpitterServiceEndpoint/getSpittlesForSpitterResponse")
    public List<Spittle> getSpittlesForSpitter(
        @WebParam(name = "arg0", targetNamespace = "")
        Spitter arg0);

}
